cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart_detail/', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('fullremove/<int:product_id>/', views.full_remove, name='full_remove'),


    
]

ecommerce_app/urls.py
from django.urls import path
from . import views
app_name = 'ecommerce_app'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/' , views.allProdCat ,name ='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/' , views.ProDetail ,name ='ProDetail'),
]

ecommerce_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Make 'shop/' the root URL by including it as ''
    path('', include('ecommerce_app.urls')),

    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views
app_name = 'search_app'

urlpatterns = [
    path('' , views.SearchResult ,name ='SearchResult'),
]

cart/models.py
from django.db import models
from ecommerce_app.models import Product

# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=100)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering =['date_added']
    def __str__(self) -> str:
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    active = models.BooleanField(default=True)
    class Meta:
        db_table = 'CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self) -> str:
        return self.product

ecommerce_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    category_description = models.TextField(blank=True)
    category_image = models.ImageField(upload_to='category_image', blank= True)

    class Meta:
        ordering = ('category_name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def get_url(self):
        return reverse('ecommerce_app:product_by_category', args=[str(self.slug)])
    
    def __str__(self):
        return str(self.category_name)

class Product(models.Model):
    product_name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    product_description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    product_image = models.ImageField(upload_to='product_image',blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerce_app:ProDetail', args=[self.category.slug,self.slug])
    
    

    class Meta:
        ordering = ('product_name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
   
    def __str__(self):
        return str(self.product_name)

search_app/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from ecommerce_app.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock :
             cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
            cart_item = CartItem.objects.create(
                 product = product,
                 quantity = 1,
                 cart = cart   
            )
            cart_item.save()
    return redirect('cart:cart_detail')



def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
          cart = Cart.objects.get(cart_id = _cart_id(request))
          cart_items = CartItem.objects.filter(cart = cart,active = True)
          for cart_item in cart_items:
               total += (cart_item.product.price * cart_item.quantity)
               counter += cart_item.quantity
    except ObjectDoesNotExist:
         pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

ecommerce_app/views.py
from django.shortcuts import get_object_or_404, render,HttpResponse
from . models import Category,Product
from django.core.paginator import Paginator, EmptyPage,InvalidPage

# Create your views here.
def allProdCat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug = c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)

    else :
        products_list = Product.objects.filter(available = True)
    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page','1')) 
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)  

    return render(request,'category.html',{'category':c_page,'products':products})


def ProDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug = c_slug, slug = product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q
from django.http import HttpResponse
# Create your views here.


def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q', '')
        products =Product.objects.all().filter(Q(product_name__contains = query) | Q(product_description__contains = query))
        return render(request,'search.html',{'query':query,'products': products})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    <!-- Include Bootstrap CSS and JavaScript from CDNs -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

     <!-- Include Popper.js from CDN -->
     <script src="{% static 'js/popper.min.js' %}"></script>
       
    <!-- Include custom fonts from Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Trirong" rel="stylesheet">

    <script src="https://kit.fontawesome.com/f41d2d9fb1.js" crossorigin="anonymous"></script>


    <!-- Include your local static files -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <meta name="description" content="{% block metadescription %}{% endblock %}">
</head>
<body>
  <div class="container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
      
        {% block content %}{% endblock %}

  </div>

    {% include 'footer.html' %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    This is your Shop Bag review for purchase
{% endblock %}

{% block title %}
    Bag-NexTrend Fashion|Pvt Ltd
{% endblock %}

{% block content %}
<div class="container">
    {% if cart_items %}
    <h2>Your Shopping Bag</h2>
        {% for cart_item in cart_items %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="{{ cart_item.product.product_image.url }}" alt="{{ cart_item.product.product_name }}" class="cart-image" style="max-width: 200px; max-height: 200px; margin-top: 50px; margin-bottom:50px; margin-left: 50px; margin-right: 50px;">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ cart_item.product.product_name }}</h5>
                            <p class="card-text">SKU : {{ cart_item.product.id }}</p>
                            <p class="card-text">Price: ₹{{ cart_item.product.price }}</p>
                            <div class="quantity-controls">
                                {% if cart_item.quantity < cart_item.product.stock %}
                                    <a href="{% url 'cart:add_to_cart' cart_item.product.id %}" class="plus-button">
                                        <i class="fa-solid fa-circle-plus"></i>
                                    </a>
                                {% endif %}
                                <span class="quantity">{{ cart_item.quantity }}</span>
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="minus-button">
                                    <i class="fa-solid fa-circle-minus"></i>
                                </a>
                                
                            </div><br>
                            <p class="card-text">Subtotal: ₹{{ cart_item.sub_total }}</p>
                            <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="trash-icon">
                                <i class="fa-regular fa-trash-can trash-icon"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="cart-summary col-md-12">
            <p>Total Items: {{ counter }}</p>
            <p>Total Price: ₹{{ total }}</p>
            <a href="" class="btn btn-success">Place Order</a>
            <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-primary">Add items</a>
        </div>
    {% else %}
    <div class="text-center">
        <p><b>Your Shopping Bag is empty.</b></p>
        <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-success">Continue Shopping</a>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{ category.category_description|truncatewords:155 }}
    {% else %}
        Welcome to NexTrend Fashion where you can buy different items...
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.category_name }} - NexTrend Fashion
    {% else %}
        See our new collections - NexTrend Fashion
    {% endif %}
{% endblock %}

{% block content %}
    <div class="container content">
        {% if category %}
            <div>
                <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-primary">Our Product Collections</a>
            </div>
            
            <div>
                <img src="{{ category.category_image.url }}" alt="{{ category.category_name }}" class="category-image">
            </div>
            
            <div>
                <h1 class="category-title">{{ category.category_name }}</h1>
                <p class="category-description">{{ category.category_description }}</p>
            </div>
        </div>
    {% else %}
        <div>
            <img src="{% static 'img/banner3.png' %}" alt="Our Products" class="category-image">
            <img src="{% static 'img/ajio.png' %}" alt="Our Products" class="category-image">
        </div>
        <div>
            <h1 class="category-title">Our Product Collections</h1>
            <p class="category-description">
                Explore our wide range of high-quality products, carefully curated to meet your needs and preferences. Whether you're looking for stylish clothing, cutting-edge electronics, or unique home decor, we have something for everyone. With a commitment to quality and customer satisfaction, we take pride in offering you the best selection. Discover the perfect items that complement your lifestyle and make your shopping experience truly exceptional.
            </p>
        </div>
    </div>

    {% endif %}
    
    <div class="container content">
        <div class="row">
            {% for product in products.object_list %}
                <div class="col-lg-3 col-md-4 col-sm-6 product-item">
                    <a href="{{ product.get_url }}">
                        <img src="{{ product.product_image.url }}" alt="{{ product.product_name }}">
                    </a>
                    <h4>{{ product.product_name }}</h4>
                    <p>₹{{ product.price }}</p>
                </div>
            {% endfor %}
        </div>
            <div class="pagination">
            {% if products.paginator.num_pages > 1 %}
                <hr>
                <ul class="pagination-list">
                    {% for pg in products.paginator.page_range %}
                        <li class="page-item {% if products.number == pg %} active {% endif %}">
                            <a href="?page={{ pg }}" class="page-link">{{ pg }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        
        {% endif %}      
    </div>
{% endblock %}

templates/footer.html
<div class="copyright">
    <center><p>&copy; Shopbag pvt ltd. All rights received</p></center>
</div>

templates/header.html
{% load static %}

<header>
    <center>
        <a href="{% url 'ecommerce_app:allProdCat' %}"><img src="{% static 'img/NexTrend.png' %}" alt="logoimage" width="250" height="250"></a>
    </center>
</header>

templates/navbar.html
{% load static %}

<!-- Your navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'ecommerce_app:allProdCat' %}">
        <img src="{% static 'img/NexTrendlogo.png' %}" alt="logoimage" width="50" height="50">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#">Home</a>
            </li>
            <li class="nav-item dropdown {% if 'ecommerce_app' in request.path %} active {% endif %}">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'ecommerce_app:allProdCat' %}">All Products</a>
                    <div class="dropdown-divider"></div>
                    {% for category in links %}
                        <a class="dropdown-item" href="{{ category.get_url }}">{{ category.category_name }}</a>
                    {% endfor %}
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-bag-shopping"></i>({{item_count}})</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="GET">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search for products,brand and more" name="q" aria-label="Search" style="width: 300px";>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-sharp fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{ product.product_description|truncatewords:155 }}
{% endblock %}

{% block title %}
    {{ product.product_name }} - NexTrend Fashion
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'ecommerce_app:allProdCat' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{{ product.category.get_url }}">{{ product.category }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ product.product_name }}</li>
                </ol>
            </nav>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-6">
            <img src="{{ product.product_image.url }}" alt="{{ product.product_name }}" class="product-image">
        </div>
        <div class="col-lg-6">
            <h1 class="product-title">{{ product.product_name }}</h1>
            <p class="product-price">₹{{ product.price }}</p>
            <p class="product-details">About this item</p>
            <p class="product-description">{{ product.product_description }}</p>
            {% if product.stock <= 0 %}
                <p class="out-of-stock"><b>Out of Stock</b></p>
            {% else %}
            <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-primary">Add to Bag</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Shop with NexTrend Fashion
{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}
<div class="container content">
    <div>
        <p class="search_text">You have searched for: <b>"{{ query }}"</b></p>
    </div>
    <div class="row">
        {% for product in products %}
            <div class="col-lg-3 col-md-4 col-sm-6 product-item">
                <a href="{{ product.get_url }}">
                    <img src="{{ product.product_image.url }}" alt="{{ product.product_name }}">
                </a>
                <h4>{{ product.product_name }}</h4>
                <p>₹{{ product.price }}</p>
            </div>
        {% empty %}
            <div class="col-12">
                <p class="search_text">0 results found</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}